site_name: nsecdopamine
site_url: https://nsecdopamine.github.io
theme:
  name: terminal
  palette: dark
  features:
    - navigation.top.hide
nav:
  - inicio: index.md
  - deltamesh: deltamesh.md
  - otros: projects.md
